<?php

namespace ContainerVg0vx7r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OTFf95Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OTFf_95' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OTFf_95'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'quizzHistory' => ['privates', '.errored..service_locator.OTFf_95.App\\Entity\\QuizzHistory', NULL, 'Cannot autowire service ".service_locator.OTFf_95": it needs an instance of "App\\Entity\\QuizzHistory" but this type has been excluded in "config/services.yaml".'],
            'quizzHistoryRepository' => ['privates', 'App\\Repository\\QuizzHistoryRepository', 'getQuizzHistoryRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'quizzHistory' => 'App\\Entity\\QuizzHistory',
            'quizzHistoryRepository' => 'App\\Repository\\QuizzHistoryRepository',
            'repository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
