<?php

namespace ContainerVg0vx7r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizzControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\QuizzController' shared autowired service.
     *
     * @return \App\Controller\QuizzController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/QuizzController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/MailerService.php';

        $container->services['App\\Controller\\QuizzController'] = $instance = new \App\Controller\QuizzController(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \App\Services\MailerService(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'))));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\QuizzController', $container));

        return $instance;
    }
}
